apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5
  labels:
    app: yolo5
spec:
  selector:
    matchLabels:
      app: yolo5
  template:
    metadata:
        labels:
          app: yolo5
    spec:
      containers:
      - name: yolo5
        image: 933060838752.dkr.ecr.us-east-2.amazonaws.com/saraa-yolo5:14
        env:
          - name: BUCKET_NAME
            value: "saraa-bucket"
          - name: TELEGRAM_APP_URL
            value: "http://polybot-service.saraa:8443"
          - name: SQS_QUEUE_NAME
            value: "saraa-predictionReq-queue"
        resources:
          requests:
            cpu: 70m
            memory: 70Mi
          limits:
            cpu: 5
            memory: 5Gi